# Generated by Django 5.2.3 on 2025-06-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelmanagement',
            old_name='name',
            new_name='model_name',
        ),
        migrations.RemoveField(
            model_name='modelmanagement',
            name='id',
        ),
        migrations.RemoveField(
            model_name='modelmanagement',
            name='user',
        ),
        migrations.AddField(
            model_name='modelmanagement',
            name='model_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
